### ISSUE TITLE
Unable to halHostRegister: 65534

### ISSUE THREAD

**Issue by GoDiao** [LMCache/LMCache-Ascend#91]
Hi I try to run lmcache on ` v0.10.2rc1-openeuler`, while I meet ` RuntimeError: register ptr failed`.

I have added the `IPC_LOCK` flag to run the docker, but still cannot.

My current driver version is npu-smi 23.0.6, must I upgrade that to 24?

**Comment by richard4fan** [comment]
I think you'd better upgrade the driver version to 24.  facing the same issue before, but solved by upgrade driver and run docker with privilege(using  --privileged to start docker).

**Comment by chloroethylene** [comment]
Yes. actually at least 24.1.0. Better if upgrade to newest version 25.3

**Comment by Mr-Xiao2021** [comment]
> Yes. actually at least 24.1.0. Better if upgrade to newest version 25.3

 Atlas A2 A800T , with CANN version 8.3.RC1, and driver version
```bash
$ cat /usr/local/Ascend/driver/version.info
Version=24.1.rc3
ascendhal_version=7.35.23
aicpu_version=1.0
tdt_version=1.0
log_version=1.0
prof_version=2.0
dvppkernels_version=1.1
tsfw_version=1.0
Innerversion=V100R001C19SPC001B124
compatible_version=[V100R001C13],[V100R001C15],[V100R001C17],[V100R001C18],[V100R001C19]
compatible_version_fw=[7.0.0,7.5.99]
package_version=24.1.rc3
```

I built the container strictly following the docker/Dockerfile.a2.openEuler instructions, but I still encountered the same error:

```log
(EngineCore_DP0 pid=202778) [2026-01-08 20:23:02,711] LMCache INFO: use mla: False, kv shape: (48, 2, 256, 4, 128), num_draft_layers:0 (vllm_v1_adapter.py:77:lmcache_ascend.integration.vllm.vllm_v1_adapter)
(EngineCore_DP0 pid=202778) [2026-01-08 20:23:02,728] LMCache INFO: Creating LMCacheEngine instance vllm-instance (cache_engine.py:1372:lmcache.v1.cache_engine)
(EngineCore_DP0 pid=202778) [2026-01-08 20:23:02,728] LMCache INFO: NUMA mapping for instance vllm-instance: None (cache_engine.py:1375:lmcache.v1.cache_engine)
(EngineCore_DP0 pid=202778) [2026-01-08 20:23:02,730] LMCache INFO: sending cache usage stats to http://stats.lmcache.ai:8080/cache-usage (usage_context.py:285:lmcache.usage_context)
(EngineCore_DP0 pid=202778) [2026-01-08 20:23:02,731] LMCache INFO: Creating LMCacheEngine with config: {'chunk_size': 256, 'local_cpu': True, 'max_local_cpu_size': 5.0, 'local_disk': None, 'max_local_disk_size': 0.0, 'remote_url': None, 'remote_serde': 'naive', 'use_layerwise': False, 'save_decode_cache': False, 'pre_caching_hash_algorithm': 'builtin', 'enable_blending': False, 'blend_recompute_ratios': None, 'blend_thresholds': None, 'blend_check_layers': None, 'blend_min_tokens': 256, 'blend_special_str': ' # # ', 'enable_p2p': False, 'p2p_host': None, 'p2p_init_ports': None, 'p2p_lookup_ports': None, 'enable_controller': False, 'lmcache_instance_id': 'lmcache_default_instance', 'controller_pull_url': None, 'controller_reply_url': None, 'lmcache_worker_ports': None, 'lmcache_worker_heartbeat_delay_time': 10, 'lmcache_worker_heartbeat_time': None, 'enable_pd': False, 'pd_role': None, 'pd_buffer_size': None, 'pd_buffer_device': None, 'pd_peer_host': None, 'pd_peer_init_port': None, 'pd_peer_alloc_port': None, 'pd_proxy_host': None, 'pd_proxy_port': None, 'transfer_channel': None, 'nixl_backends': None, 'nixl_buffer_size': None, 'nixl_buffer_device': None, 'weka_path': None, 'gds_path': None, 'cufile_buffer_size': None, 'audit_actual_remote_url': None, 'internal_api_server_host': '0.0.0.0', 'extra_config': None, 'save_unfull_chunk': True, 'blocking_timeout_secs': 10, 'external_lookup_client': None, 'py_enable_gc': True, 'cache_policy': 'LRU', 'numa_mode': None, 'enable_async_loading': False, 'internal_api_server_enabled': False, 'internal_api_server_port_start': 6999, 'priority_limit': None, 'internal_api_server_include_index_list': None, 'internal_api_server_socket_path_prefix': None, 'plugin_locations': None, 'external_backends': None, 'lookup_timeout_ms': 3000, 'hit_miss_ratio': None} (cache_engine.py:87:lmcache.v1.cache_engine)
(EngineCore_DP0 pid=202778) [2026-01-08 20:23:02,733] LMCache INFO: Initializing LRUCachePolicy (lru.py:20:lmcache.v1.storage_backend.cache_policy.lru)
(EngineCore_DP0 pid=202778) [2026-01-08 20:23:02,733] LMCache INFO: NUMA mapping None (local_cpu_backend.py:278:lmcache.v1.storage_backend.local_cpu_backend)
Unable to halHostRegister: 65534 . Please ensure your driver version >= 24.1.0
(EngineCore_DP0 pid=202778) /usr/local/python3.11.13/lib/python3.11/contextlib.py:167: ResourceWarning: Unclosed context <zmq.Context() at 0xfffce8f08c50>
```
